---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbt-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbt-db
  template:
    metadata:
      labels:
        app: hbt-db
    spec:
      containers:
      - name: hbt-mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Abh1navas" # replace with your password
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
