---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbt-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbt-db
  template:
    metadata:
      labels:
        app: hbt-db
    spec:
      containers:
      - name: hbt-mssql
        command:
          - /bin/bash
          - -c
          - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
          - chmod +x /opt/mssql/bin/permissions_check.sh
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "Abh1navas" # replace with your password
        volumeMounts:
        - name: mssql-persistent-storage
          mountPath: /var/opt/mssql
        resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
      volumes:
      - name: mssql-persistent-storage
        persistentVolumeClaim:
          claimName: nfs-db-pvc

